spring:
  application:
    name: SAP-RFC-TEMPLATE
management:
  security:
    enabled: false
endpoints:
  health:
    enabled: true
  camelroutes:
    enabled: true
    read-only: true
server:
  port: 9191
eureka:
  client:
    service-url:  
      defaultZone: http://oupeureka:8761/eureka/
  instance:
    prefer-ip-address: true